services:
  heartfive:
    build: .
    ports:
      - "2567:2567"
    environment:
      - NODE_ENV=production
      - PORT=2567
      - WEB_URL=${WEB_URL:-http://localhost:2567}
    restart: unless-stopped
